global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets:
        - 'order:8080'
        labels:
          instance: order-service