global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'hello-service'
    static_configs:
      - targets:
        - 'host.docker.internal:8080'
        labels:
          instance: hello
  - job_name: 'my_mac'
    static_configs:
      - targets:
        - 'host.docker.internal:9100'