services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  user_service:
    image: user_service:1.0
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=user_service
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://otel-collector:4317
      # interval time OTLP endpoint for metrics
      - OTEL_METRIC_EXPORT_INTERVAL=1000
      - MONGO_URI=mongodb://mongo:27017/test?connect=direct

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.128.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./configs/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
      - 4318:4318
  
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-otlp-receiver # Enables the OTLP receiver
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686