### Create a user
POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### call products
GET http://localhost:8080/call/products