global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'demo-tracing'
    static_configs:
      - targets:
        - 'demo_tracing:8080'
        labels:
          instance: demo-tracing